version: '3.9'

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./jobhive.war:/usr/local/tomcat/webapps/jobhive.war
    depends_on:
      - mysql
    command: ["/bin/bash", "-c", "sleep 30 && catalina.sh run"]
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - ./initial_RFU.sql:/docker-entrypoint-initdb.d/initial_RFU.sql
    restart: always
