version: '3.9'

services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tomcat
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    command: ["/bin/bash", "-c", "sleep 30 && catalina.sh run"]
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306"
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: admin123
    volumes:
      - ./config/Database:/docker-entrypoint-initdb.d
    restart: always
    
  jobhive-server:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: jobhive
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    command: ["nginx", "-g", "daemon off;"]
    restart: always
